config/routes.rb
Rails.application.routes.draw do
 
  resources :videos
  get 'videos/new' => 'videos#new'
  get 'visao' =>'visao#send_data'
  get '/videos/:id/like' => 'videos#like'
  get '/videos/:id/dislike' => 'videos#dislike'
post 'videos/new'  =>   'videos#upload'

  

resources :sessions  
	 get 'sessions/new'
   get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'usuarios/new'

  resources :usuarios
  get 'static_pages/home'

  get 'static_pages/help'
  get 'assine' => 'usuarios#new'
  resources :usuarios

end

app/controllers/sessoes_controller.rb
class SessoesController < ApplicationController
  	def new
  	end
  	def create
		sessao = Sessao.find_by(email: params[:sessao][:email].downcase)
    if usuario && usuario.authenticate(params[:sessao][:password])
      # Log the user in and redirect to the user's show page.
    else
      algo deu errado
    render 'new'
     end
  	end
	
	def destroy
  	end
end

app/helpers/sessoes_helper.rb
module SessoesHelper
end

app/views/sessoes/new.html.erb
<% provide(:title, "login") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>Novo por aqui? <%= link_to "assine!", assine_path %></p>
  </div>
</div>

app/views/sessoes/new.html.haml
- provide(:title, "login")
%h1 Log in
.row
  .col-md-6.col-md-offset-3
    = form_for(:session, url: login_path) do |f|
      = f.label :email
      = f.email_field :email, class: 'form-control'
      = f.label :password
      = f.password_field :password, class: 'form-control'
      = f.submit "Log in", class: "btn btn-primary"
    %p
      Novo por aqui? #{link_to "assine!", assine_path}