config/routes.rb
Rails.application.routes.draw do
 
  resources :videos
  get 'videos/new' => 'videos#new'
  get 'visao' =>'visao#send_data'
  get '/videos/:id/like' => 'videos#like'
  get '/videos/:id/dislike' => 'videos#dislike'
post 'videos/new'  =>   'videos#upload'

  

resources :sessions  
	 get 'sessions/new'
   get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'usuarios/new'

  resources :usuarios
  get 'static_pages/home'

  get 'static_pages/help'
  get 'assine' => 'usuarios#new'
  resources :usuarios

end

app/models/video.rb
class Video < ActiveRecord::Base
#	self.primary_key = "video_id"
	
	has_attached_file :data,
  url: '/videos/:id/:style/:basename.:extension', # whatever you want
  styles: {
    poster: { size: '640x480', format: 'jpg' }, # this takes a snapshot of the video to have as your poster
    v_large_webm: { geometry: '640x480', format: 'webm' }, # your webm format
    v_large_mp4: { geometry: '640x480', format: 'mp4' }, # your mp4 format
    v_large_MOV: { geometry: '640x480', format: 'MOV' } # your mp4 format

  } , :processors => [:ffmpeg]

	has_many :usuarios_videos
	has_many :usuarios, :through => :usuarios_videos
	validates_attachment_presence :data
	validates_attachment_size :data, less_than: 100.megabytes # if you want a max file size
	validates_attachment_content_type :data, content_type: /\Avideo\/.*\Z/ # or you can specify individual content types you want to allow
	

  end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
 #before_action :log_in
  #before_action :set_video, only: [:show, :edit, :like, :dislike]
wrap_parameters :video, include: [:id, :titulo, :criado_em, :descricao, :thumbnail_file_name, :thumbnail_updated_at, :published, :created_at, :updated_at, :data, :usuarios_videos_id, :data_file_name, :data_content_type, :data_file_size, :data_updated_at]


  # All published videos
  def index
    @videos = @Usuario.videos
      end

  def show
	@video=Video.find(params[:id])

	render stream:true

  end

  def new
	 
     @video = Video.new
         flash[:notice] = 'Video was saved.'
   
  end

  def edit
  end

  def create
    @video = Video.create(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # Likes video, increment likes count
  def like
    @video.like!
  end

  # Dislikes video, increment likes count
  def dislike
    @video.dislike!
  end
   def log_in(usuario)
	session[:usuario_id] = usuario.id
   end
# POST /upload
  # POST /upload.json
  def upload
    @video = Video.new(video_params)
		
    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def usuarios_videos
  	@usuario = Usuario.find(session[:usuario_id])
	@videos = Video.find(params[:id])
        @usuarios_videos = [@usuario, @videos]
  end
  def set_video
    @videos = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:id, :titulo, :criado_em, :descricao, :thumbnail_file_name, :thumbnail_updated_at, :published, :created_at, :updated_at, :data, :usuarios_videos_id, :data_file_name, :data_content_type, :data_file_size, :data_updated_at)
  end
  

end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= f.text_field :data_content_type %>
  </div>
  <div class="field">
    <%= f.label :file_contents %><br>
    <%= f.text_field :descricao %>
  </div>
  
  <%= form_for(@video) do |f| %>
  <div class="field">
    <%= f.file_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<%= form_tag({action: :upload}, multipart: true) do %>
  <%= file_field_tag 'file' %>
<% end %>
 


<% end %>
<% end %>

app/views/videos/index.haml
.container
  .row
    - @videos.each do |video|
      .col-md-3.thumb.video-thumb{ 'data-video-id': video.id }
        .likes
          %span.likes-count= video.likes
          %span.glyphicon.glyphicon-heart
        = link_to video, class: 'thumbnail' do
          = image_tag video.thumbnail.url(:medium_nr)
  .row
    .col-md-12
      .pull-right
        = link_to 'Upload new video', new_video_url, class: 'btn btn-primary'

app/views/videos/index.html.erb
<div class="container">
  <div class="row">
    <% @videos.each do |video| %>
      <div class="col-md-3 thumb video-thumb" data-video-id="<%= video.id %>">
        <div class="likes">
          <span class="likes-count">
            <%= video.likes %>
          </span>
          <span class="glyphicon glyphicon-heart"></span>
        </div>
        <%= link_to video, class: 'thumbnail' do %>
          <%= image_tag video.thumbnail.url(:medium_nr) %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="pull-right">
        <%= link_to 'Upload new video', new_video_url, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/videos/new.haml
.container
  .row
    .col-md-6.col-sm-12
      %h2 Upload new video

      = simple_form_for @video, html: { multipart: true } do |f|
        = f.input :name
        = f.input :video_file, as: :file
        = f.button :submit, class: 'btn-primary', value: 'Upload Video'

app/views/videos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <h2>Upload new video</h2>
      <%= form_for Video.new, html: { multipart: true } do |f| %>
         
	 <%= render 'form' %>

        
        <%= f.button :submit, class: 'btn-primary', value: 'Upload Video' %>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/show.haml
.container
  .row.video-full{ 'data-video-id': @video.id }
    .col-md-10
      %h1= @video.name
      %p.small
        = link_to 'Back to videos' ,videos_path

      - if @video.all_formats_encoded?
        %video#my-video.video-js{:controls => "", "data-setup" => "{}", :height => "264", :preload => "auto", :width => "640"}
          %source{:src => @video.mp4_file.url, :type => "video/mp4"}
          %source{:src => @video.webm_file.url, :type => "video/webm"}
          %source{:src => @video.ogg_file.url, :type => "video/ogg"}
          %p.vjs-no-js
            To view this video please enable JavaScript, and consider upgrading to a web browser that
            %a{:href => "http://videojs.com/html5-video-support/", :target => "_blank"} supports HTML5 video
      - else
        %p Video is still being encoded.
    .col-md-2
      %h1
        %span.likes-count= @video.likes
        %span.glyphicon.glyphicon-heart

app/views/videos/show.html.erb
<div class="container">
 
    <div class="col-md-10">
      <h1>
        <%= @video.titulo %>
	  </source>
</video>
	<%= video_tag bscene.video.url(:medium), controls: true, style: "max-width: 100%;" %>
      </h1>
      <p class="small">
        <%= link_to 'Back to videos' ,videos_path %>
      </p>
      <% if @video.all_formats_encoded? %>
        <video class="video-js" data-setup="{ %>" height="264" id="my-video" preload="auto" width="640">
          <source src="<%= @video.mp4_file.url %>" type="video/mp4"></source>
          <source src="<%= @video.webm_file.url %>" type="video/webm"></source>
          <source src="<%= @video.ogg_file.url %>" type="video/ogg"></source>
	  <source src="<%= @video.MOV_file.url %>" type="video/MOV"></source>
	 <source src="<%= @video.m4v_file.url %>" type="video/m4v"></source>

          <p class="vjs-no-js">

          <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a web browser that
            <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
          </p>
        </video>
      <% else %>
        <p>Video is still being encoded.</p>
      <% end %>
    </div>
    <div class="col-md-2">
      <h1>
        <span class="likes-count">
          <%= @video.likes %>
        </span>
        <span class="glyphicon glyphicon-heart"></span>
      </h1>
    </div>
  </div>
</div>