config/routes.rb
Rails.application.routes.draw do
 
  resources :videos
  get 'videos/new' => 'videos#new'
  get 'visao' =>'visao#send_data'
  get '/videos/:id/like' => 'videos#like'
  get '/videos/:id/dislike' => 'videos#dislike'
post 'videos/new'  =>   'videos#upload'

  

resources :sessions  
	 get 'sessions/new'
   get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'usuarios/new'

  resources :usuarios
  get 'static_pages/home'

  get 'static_pages/help'
  get 'assine' => 'usuarios#new'
  resources :usuarios

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	#self.primary_key = "usuario_id"
	has_many :usuarios_videos
	has_many :videos, :through => :usuarios_videos

	attr_accessor :remember_token
	before_save { self.email = email.downcase }
	validates :nome, presence: true, length: {maximum: 50}
	EXPRESSAO_REGULAR_VALIDA = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length:{maximum: 255},
	 format: { with: EXPRESSAO_REGULAR_VALIDA },

	uniqueness: {case_sensitive: false}
	has_secure_password
  	validates :password, presence: true, length: { minimum: 6 }
#	has_attached_file :video, :styles =>{medium = "300x300" =>:thumb} 

	# Returns the hash digest of the given string.
  def Usuario.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Retorna um token aleatório
  def Usuario.new_token
    SecureRandom.urlsafe_base64
  end

  # Remember um usuario no database for use in persistent sessions.
  def remember
    self.remember_token = Usuario.new_token
    update_attribute(:remember_digest, Usuario.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  def forget
	update_attribute(:remember_digest, nil)
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
skip_before_filter :verify_authenticity_token, :only => :create 
 before_action :set_usuario, only: [:show, :edit, :update, :destroy]
	wrap_parameters :person, include: [:nome, :email, :password]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
	@usuario=Usuario.find(params[:id])
	
	#debugger
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end
    
    def set_current_usuario
	@usuario=current_usuario
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :email, :password)
	
    end
   def video
   	 params.require(:usuario).permit(:video)

   end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
	 # Returna o Gravatar para usuario
  def gravatar_for(usuario)
    gravatar_id = Digest::MD5::hexdigest(usuario.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: usuario.nome, class: "gravatar")
  end
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/home.html.erb
<div class="center jumbotron">
  <h1>Bem-vindo</h1>

  <h2>
    Esta é a página inicial da Academia de música online. Seja bem-vindo!
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    
  </h2>

  <%= link_to "Assine agora", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>É novo aqui?</h1>
<% provide(:title, 'assine') %>
<h1>Assine já!</h1>
<form accept-charset="UTF-8" action="/usuarios" class="new_usuario"
      id="new_usuario" method="post">
  <input name="utf8" type="hidden" value="&#x2713;" />
  <input name="authenticity_token" type="hidden"
         value="NNb6+J/j46LcrgYUC60wQ2titMuJQ5lLqyAbnbAUkdo=" />
  <label for="usuario_nome">Nome</label>
  <input id="usuario_nome" name="usuario[nome]" type="text" />

  <label for="usuario_email">Email</label>
  <input id="usuario_email" name="usuario[email]" type="email" />

  <label for="usuario_password">Password</label>
  <input id="usuario_password" name="usuario[password]"
         type="password" />

  <label for="usuario_password_confirmation">Confirme seu password</label>
  <input id="usuario_password_confirmation"
         name="usuario[password_confirmation]" type="password" />

  <input class="btn btn-primary" name="commit" type="submit"
         value="Create my account" />
</form>


<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<% provide(:title, @usuario.nome) %>
<div class="row">
  <aside class="col-md-4">
    <section class="usuario_info">
<h1>
  <%= gravatar_for @usuario %>
  <%= @usuario.nome %>
</h1>
</section>
  </aside>
</div>
<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>
<div class="body">
	
	<% if false%> <%= video_tag (@Usuario.video :size => "320x240", :controls => true) %></video>
   <% end %>

</div>
<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>